name: 'mdtopdf-action'
description: 'Use mdtopdf on GitHub Actions'
author: 3rdJCG

inputs:
  root_file:
    description: The root markdown file to be compiled
    required: true
  working_directory:
    description: The working directory for the latex compiler to be invoked
  mode:
    description: mdtopdf output mode to be used
    default: mdtopdf
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.root_file }}
    - ${{ inputs.working_directory }}
    - ${{ inputs.mode }}