# This is a basic workflow to help you get started with Actions

name: test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Generate PDF documents
      uses: ./
      with:
        working_directory: test
        mode: mdtopdf
        root_file: test.md
    - name: Generate TeX documents
      uses: ./
      with:
        working_directory: test
        mode: mdtotex
        root_file: test.md
    - name: Generate HTML documents
      uses: ./
      with:
        working_directory: test
        mode: mdtohtml
        root_file: test.md
    - name: Generate DOCX documents
      uses: ./
      with:
        working_directory: test
        mode: mdtodocx
        root_file: test.md
    - name: Commit files
      run: |
        git add test/test.pdf
        git add test/test.tex
        git add test/test.html
        git add test/test.docx
        git config --local user.email "3rdJCG@gmail.com"
        git config --local user.name "3rdJCG"
        git commit -m "Generate test.pdf" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
